# Generated by Django 5.0.7 on 2024-09-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Default Company', max_length=100)),
                ('job_name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('salary', models.CharField(max_length=50, null=True)),
                ('experience_level', models.CharField(max_length=100, null=True)),
                ('skills', models.TextField(null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(max_length=100)),
                ('requirement', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePython',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceReact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('language', models.JSONField(default=list)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('hobbies', models.JSONField(default=list)),
                ('project', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
    ]
