# Generated by Django 5.0.7 on 2024-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('salary', models.CharField(max_length=50)),
                ('experience_level', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=50)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
