# Generated by Django 5.0.7 on 2024-09-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_jobpost_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='skills',
            new_name='skillss',
        ),
    ]
