# Generated by Django 5.0.7 on 2024-08-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jobpost_delete_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default='Default Company', max_length=100),
        ),
    ]
