# Generated by Django 5.0.7 on 2024-09-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jobpost_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
