# Generated by Django 5.0.7 on 2024-09-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_skills_resume_skillss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
