# Generated by Django 5.0.7 on 2024-09-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='skills',
            field=models.TextField(default='[]'),
        ),
    ]
