# Generated by Django 5.0.7 on 2024-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_jobpost_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('language', models.JSONField(default=list)),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('hobbies', models.JSONField(default=list)),
                ('project', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
