# Generated by Django 5.0.7 on 2024-09-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_resource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='ResourcePython',
        ),
    ]
