# Generated by Django 5.0.7 on 2024-09-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_resume_hobby_experience_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='contact',
            new_name='contactnumber',
        ),
    ]
