# Generated by Django 5.0.7 on 2024-09-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_resourcereact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
    ]
