# Generated by Django 5.0.7 on 2024-09-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_experience_resume_remove_hobby_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
