# Generated by Django 5.0.7 on 2024-09-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_resume_education_remove_resume_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='hobbies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='project',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
